__author__ = "Kristina Sungeun Song"
__email__ = "kristina.song@usherbrooke.ca"

"""
Modified from the CRSSANT pipeline https://github.com/zhipenglu/CRSSANT; https://github.com/whl-usc/rna2d3d
"""


##### store paths and user-specific variables #####
configfile: "config/config.yaml"


#############################
## Load rules
#############################

include: "rules/download.smk"
include: "rules/preprocessing.smk"
include: "rules/mapping.smk"
include: "rules/stats.smk"
include: "rules/crssant.smk"


rule all:
    input:
        #### Step 1: Download FASTQ files from GEO -- may require multiple runs
        PARIS_fq = expand("resources/fastq/PARIS/{accession}.fastq.gz",accession=config['PARIS']),
        PARIS2_fq = expand("resources/fastq/PARIS2/{accession}.fastq.gz",accession=config['PARIS2']),
        LIGR_fq = expand("resources/fastq/LIGR/{accession}.fastq.gz",accession=config['LIGR']),
        SPLASH_fq = expand("resources/fastq/SPLASH/{accession}.fastq.gz",accession=config['SPLASH']),
        #### Step 2: Download git repo -- use profile_local
        icSHAPE_git = "resources/icSHAPE/icSHAPE_pipeline.pl",
        #### Step 3: CRSSANT
        # FastQC
        PARIS_qc = expand("results/fastqc/{qc_type}/PARIS/{accession}_fastqc.html",accession=config['PARIS'],qc_type=['raw','preprocessed']),
        PARIS2_qc = expand("results/fastqc/{qc_type}/PARIS2/{accession}_fastqc.html",accession=config['PARIS2'],qc_type=['raw','preprocessed']),
        LIGR_qc = expand("results/fastqc/preprocessed/LIGR/{accession}_fastqc.html",accession=config['LIGR']),
        SPLASH_qc = expand("results/fastqc/preprocessed/SPLASH/{accession}_fastqc.html",accession=config['SPLASH']),
        # Mapping stats
        #PARIS_len_stats = expand("results/stats/PARIS/{accession}/{accession}_{stats}len.pdf",accession=config['PARIS'],stats=['seg','gap']),
        #PARIS2_len_stats = expand("results/stats/PARIS2/{accession}/{accession}_{stats}len.pdf",accession=config['PARIS2'],stats=['seg','gap']),
        #LIGR_len_stats = expand("results/stats/LIGR/{accession}/{accession}_{stats}len.pdf",accession=config['LIGR'],stats=['seg','gap']),
        #SPLASH_len_stats = expand("results/stats/SPLASH/{accession}/{accession}_{stats}len.pdf",accession=config['SPLASH'],stats=['seg','gap']),
        # Assembly
        #PARIS_asm = expand("results/crssant/PARIS/{accession}/{accession}_pri_gapm_filtered_tg.sam",accession=config['PARIS']),
        #PARIS2_asm = expand("results/crssant/PARIS2/{accession}/{accession}_pri_gapm_filtered_tg.sam",accession=config['PARIS2']),
        #LIGR_asm = expand("results/crssant/LIGR/{accession}/{accession}_pri_gapm_filtered_tg.sam",accession=config['LIGR']),
        #SPLASH_asm = expand("results/crssant/SPLASH/{accession}/{accession}_pri_gapm_filtered_tg.sam",accession=config['SPLASH'])