__default__:
  account: def-scottmic
  mail-user: kristina.song@usherbrooke.ca
  mail-type: FAIL
  job-name: "smk_{rule}_{wildcards}"
  time: 180 # minutes
  nodes: 1
  ntasks: 1
  mem: 32000M
  cpus-per-task: 8
  output: results/logs/slurmout/{rule}.{wildcards}.out
  error: results/logs/slurmout/{rule}.{wildcards}.err


trim3_PARIS:
  time: 600
  cpus-per-task: 32
  mem: 32G

trim5_PARIS:
  time: 600
  cpus-per-task: 32
  mem: 32G

trim3_PARIS2:
  time: 600
  cpus-per-task: 32
  mem: 32G

trim5_PARIS2:
  time: 600
  cpus-per-task: 32
  mem: 32G

STAR_index:
  cpus-per-task: 32
  mem: 128G
  time: 600

STAR_align_1:
  cpus-per-task: 32
  mem: 128G
  time: 600

STAR_align_2:
  cpus-per-task: 32
  mem: 128G
  time: 600

classify_alignments_1:
  cpus-per-task: 32
  mem: 128G
  time: 600

classify_alignments_2:
  cpus-per-task: 32
  mem: 128G
  time: 600

DG_NG_assembly:
  cpus-per-task: 16
  mem: 128G
  time: 600

TG_assembly:
  cpus-per-task: 16
  mem: 128G
  time: 600
